### ISSUE TITLE
Some HEIF images fail

### ISSUE THREAD

**Issue by paxvista** [AJLoveChina/libheic#1]
Some of the new HEIF images I'm testing fail with the following error:
Could not parse HEIF file Invalid input: No 'ftyp' box
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'get_width')
![image](https://github.com/user-attachments/assets/715f8067-b406-4c5c-baae-07033f72323b)
[MtnLake.heic.zip](https://github.com/user-attachments/files/17600997/MtnLake.heic.zip)

**Comment by AJLoveChina** [comment]
Thanks @paxvista , I will take a look

**Comment by AJLoveChina** [comment]
Hi @paxvista I try to use original latest libheif library to decode the heic image, it failed too. So I can't fix it. Post an issue in libheif library - https://github.com/strukturag/libheif/issues/1361

**Comment by farindk** [comment]
As mentioned in https://github.com/strukturag/libheif/issues/1361, the image is not a HEIC file. It is a JPEG file with the wrong suffix.
